version: '2.1'
services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  registry-server:
    build: registry-server
    restart: always
    ports:
      - 8761:8761
    logging:
      options:
        max-size: "10m"
        max-file: "10"


  number-service:
    environment:
      MONGODB_PASSWORD: password123
    build: number-service
    restart: always
    ports:
      - 8000:8000
    logging:
      options:
        max-size: "10m"
        max-file: "10"

  number-mongodb:
    environment:
      MONGODB_PASSWORD: password123
    build: mongodb
    ports:
      - 26000:27017
    restart: always
    logging:
      options:
        max-size: "10m"
        max-file: "10"